import { createAction } from 'redux-actions';

// 文字列定数
export const CREATE_USER_ACCOUNT = Symbol('CREATE_USER_ACCOUNT');
export const CLICK_SUBMIT = Symbol('CLICK_SUBMIT');
export const SAVE_USER_MNEMONIC = Symbol('SAVE_USER_MNEMONIC');
export const LOGIN_USER = Symbol('LOGIN_USER');
export const LOGIN_USER_JWT = Symbol('LOGIN_USER_JWT');
export const LOGOUT_USER = Symbol('LOGOUT_USER');
export const UPDATE_USER_DATA = Symbol('UPDATE_USER_DATA');
export const SAVE_USER_DATA = Symbol('SAVE_USER_DATA');
export const SAVE_USER_PASSWORD = Symbol('SAVE_USER_PASSWORD');
export const UPDATED_USER_DATA = Symbol('UPDATED_USER_DATA');
export const REMOVE_USER_DATA = Symbol('REMOVE_USER_DATA');
export const REQUEST_DATA = Symbol('REQUEST_DATA');
export const RECEIVE_DATA_SUCCESS = Symbol('RECEIVE_DATA_SUCCESS');
export const RECEIVE_DATA_FAILED = Symbol('RECEIVE_DATA_FAILED');
export const LOGIN_SUCCESS = Symbol('LOGIN_SUCCESS');
export const LOGIN_FAILED = Symbol('LOGIN_FAILED');
export const GET_USER_PROFILE = Symbol('GET_USER_PROFILE');
export const GET_USER_BY_TOKEN = Symbol('GET_USER_BY_TOKEN');
export const UPDATED_PROFILE_DATA = Symbol('UPDATED_PROFILE_DATA');
export const PREPARED_AUTH = Symbol('PREPARED_AUTH');
export const UPDATED_PROFILE_QUESTION_DATA = Symbol('UPDATED_PROFILE_QUESTION_DATA');
export const UPDATED_PROFILE_ANSWER_DATA = Symbol('UPDATED_PROFILE_ANSWER_DATA');
export const UPDATED_PROFILE_COMMENT_DATA = Symbol('UPDATED_PROFILE_COMMENT_DATA');
export const SEND_RESET_PASSWORD_MAIL = Symbol('SEND_RESET_PASSWORD_MAIL');
export const RESET_PASSWORD = Symbol('RESET_PASSWORD');
export const ACTIVATE_USER = Symbol('ACTIVATE_USER');


export const createUserAccount = createAction(CREATE_USER_ACCOUNT);
export const clickSubmit = createAction(CLICK_SUBMIT);
export const saveUserMnemonic = createAction(SAVE_USER_MNEMONIC);
export const loginUser = createAction(LOGIN_USER);
export const loginUserJwt = createAction(LOGIN_USER_JWT);
export const logoutUser = createAction(LOGOUT_USER);
export const saveUserData = createAction(SAVE_USER_DATA);
export const saveUserPassword = createAction(SAVE_USER_PASSWORD);
export const updateUserData = createAction(UPDATE_USER_DATA);
export const updatedUserData = createAction(UPDATED_USER_DATA);
export const removeUserData = createAction(REMOVE_USER_DATA);
export const requestData = createAction(REQUEST_DATA);
export const receiveDataSuccess = createAction(RECEIVE_DATA_SUCCESS);
export const receiveDataFailed = createAction(RECEIVE_DATA_FAILED);
export const loginSuccess = createAction(LOGIN_SUCCESS);
export const loginFailed = createAction(LOGIN_FAILED);
export const getUserProfile = createAction(GET_USER_PROFILE);
export const getUserByToken = createAction(GET_USER_BY_TOKEN);
export const updatedProfileData = createAction(UPDATED_PROFILE_DATA);
export const preparedAuth = createAction(PREPARED_AUTH);
export const updatedProfileQuestionData = createAction(UPDATED_PROFILE_QUESTION_DATA);
export const updatedProfileAnswerData = createAction(UPDATED_PROFILE_ANSWER_DATA);
export const updatedProfileCommentData = createAction(UPDATED_PROFILE_COMMENT_DATA);
export const sendResetPasswordMail = createAction(SEND_RESET_PASSWORD_MAIL);
export const resetPassword = createAction(RESET_PASSWORD);
export const activateUser = createAction(ACTIVATE_USER);
